parameters:
    uneak.assetsmanager.class: Uneak\AssetsManagerBundle\Assets\AssetsManager
    uneak.assetsmanager.twig.extension.class: Uneak\AssetsManagerBundle\Twig\Extension\AssetsManagerExtension

services:

    uneak.assetsmanager:
        class: %uneak.assetsmanager.class%

    uneak.assetsmanager.twig.extension:
        class: %uneak.assetsmanager.twig.extension.class%
        arguments:
            - @uneak.assetsmanager
            - @twig
        tags:
            - { name: twig.extension }

    twig.stringloader:
        class: Twig_Loader_String
        tags:
            - { name: twig.loader }